title: MonkTalks - technology, society, beer
description: A fan site dedicated to all the speakers and staff of Monktoberfest by Redmonk.
theme: jekyll-theme-tactile
show_downloads: false
google_analytics: G-SQSVPK9E33

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary

defaults:
  - scope:
      path: "monktoberfest"
      type: "talks"
    values:
      layout: talks
      comments: false