theme: tactile
title: MonkTalks - technology, society, beer
description: A fan site dedicated to all the speakers and staff of Monktoberfest by Redmonk.
show_downloads: false
google_analytics: 

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary
